@startuml
scale 2

activate AbstractConsoleAdapter
[->AbstractConsoleAdapter : isRunning()
[<--AbstractConsoleAdapter : isRunning

deactivate AbstractConsoleAdapter

[->AbstractConsoleAdapter : execute(index)
activate AbstractConsoleAdapter
AbstractConsoleAdapter->": ActionFactory" : create(index)
activate ": ActionFactory"
create "actionExecutor : ActionExecutor"
": ActionFactory"->"actionExecutor : ActionExecutor" : <<create>>
": ActionFactory"-->AbstractConsoleAdapter : actionExecutor
deactivate ": ActionFactory"

AbstractConsoleAdapter->ReflectionUtils : createInstance(ActionQuery)
activate ReflectionUtils
ReflectionUtils-->AbstractConsoleAdapter : query

loop dla każdego pola query

AbstractConsoleAdapter -> AbstractConsoleAdapter : createOptionsForField(pole)
AbstractConsoleAdapter -> System.out : println(pole)
AbstractConsoleAdapter -> AbstractConsoleAdapter : readInput(typ pola)
AbstractConsoleAdapter -> ReflectionUtils : setField(pole, query, input)

deactivate ReflectionUtils

end

AbstractConsoleAdapter -> "actionExecutor : ActionExecutor" : execute(query)
activate "actionExecutor : ActionExecutor"
alt actionExecutor zwrócił wynik
    "actionExecutor : ActionExecutor"-->AbstractConsoleAdapter : result
    deactivate "actionExecutor : ActionExecutor"
    AbstractConsoleAdapter->System.out : println(result.toString())
else nastąpił wyjątek ShutdownRequestException
    AbstractConsoleAdapter->AbstractConsoleAdapter : shutDown()
end

deactivate AbstractConsoleAdapter

[->AbstractConsoleAdapter : readInput(type)
activate AbstractConsoleAdapter
AbstractConsoleAdapter->"SCANNER : Scanner" : nextLine()
activate "SCANNER : Scanner"
"SCANNER : Scanner"-->AbstractConsoleAdapter : line
deactivate "SCANNER : Scanner"

loop dla każdego elementu DESERIALIZATION_CHAIN jako linkClass
    AbstractConsoleAdapter->ReflectionUtils : getInstance(linkClass)
    activate ReflectionUtils
    create "link : DeserializationLink"
    ReflectionUtils->"link : DeserializationLink" : <<create>>
    ReflectionUtils-->AbstractConsoleAdapter : link
    deactivate ReflectionUtils
    AbstractConsoleAdapter->"link : DeserializationLink" : deserialize(line, type)
    activate "link : DeserializationLink"
    "link : DeserializationLink"-->AbstractConsoleAdapter : result
    deactivate "link : DeserializationLink"

    alt jeśli result != null
        [<--AbstractConsoleAdapter : result
    end
end

[<--AbstractConsoleAdapter : wyrzuć wyjątek IllegalStateException
deactivate AbstractConsoleAdapter

[->AbstractConsoleAdapter : format(result)
activate AbstractConsoleAdapter
alt jeśli result != null
[<--AbstractConsoleAdapter : result.toString()
else jeśli jednak result == null
[<--AbstractConsoleAdapter : ""
end

deactivate AbstractConsoleAdapter

[->AbstractConsoleAdapter : shutDown()
activate AbstractConsoleAdapter
AbstractConsoleAdapter->"SCANNER : Scanner" : close()
AbstractConsoleAdapter->AbstractConsoleAdapter : isRunning = false

deactivate AbstractConsoleAdapter

[->AbstractConsoleAdapter : createOptionsForField(field)
activate AbstractConsoleAdapter
alt jeśli typ to enum
[<--AbstractConsoleAdapter : wartości stałych
else
[<--AbstractConsoleAdapter : ""
end

deactivate AbstractConsoleAdapter

@enduml