@startuml
interface java.io.Serializable

class pl.cezaryregec.zoo.ZooApplication {
    + {static} main()
}

class pl.cezaryregec.zoo.console.ZooConsoleAdapter {
    + <<constructor>> ZooConsoleAdapter()
    + nextCommand()
}

interface pl.cezaryregec.zoo.console.ConsoleAdapter<Actions : ActionFactory> {
    +nextCommand()
    +isRunning() : boolean
    +execute()
}

abstract class pl.cezaryregec.zoo.console.AbstractConsoleAdapter<Actions : ActionFactory> {
    - {static} DESERIALIZATION_CHAIN : List<Class<? extends DeserializationLink>>

    #actions : Actions
    -scanner : Scanner
    -isRunning : boolean

    # <<constructor>> AbstractConsoleAdapter(Actions actions)
    +{abstract} nextCommand()
    +isRunning() : boolean
    +execute()
    #<Type : Object> readInput(type : Class<Type>) : Type
    #format(result : ResultDto) : String
    #shutDown()
    -createOptionsForField(field: Field) : String
}

pl.cezaryregec.zoo.console.ConsoleAdapter <|.. pl.cezaryregec.zoo.console.AbstractConsoleAdapter

class pl.cezaryregec.zoo.utils.ReflectionUtils {
    -{static} IMPLEMENTATIONS : Map<Class, Object>
    -<<constructor>> ReflectionUtils()
    +{static} <Type : Object> bindInstance(type : Class<Type>, instanceClass : Class<? extends Type>)
    +{static} <Type : Object, Instance : Type> bindInstance(type : Class<Type>, instance: Instance)
    +{static} <Type : Object> getInstance(type : Class<Type>) : Type
    +{static} <Type : Object> createInstance(type : Class<Type>) : Type
    +{static} setField(field : Field, object : Object, value : Value)
}

class pl.cezaryregec.zoo.exception.ShutdownRequestException

pl.cezaryregec.zoo.exception.ShutdownRequestException <|-- java.lang.RuntimeException
pl.cezaryregec.zoo.console.AbstractConsoleAdapter --> pl.cezaryregec.zoo.exception.ShutdownRequestException : <<use>>

pl.cezaryregec.zoo.ZooApplication --> pl.cezaryregec.zoo.console.ZooConsoleAdapter : <<use>>
pl.cezaryregec.zoo.console.AbstractConsoleAdapter <|-- pl.cezaryregec.zoo.console.ZooConsoleAdapter : <<bind>> \n Actions -> ZooActionFactory

pl.cezaryregec.zoo.console.AbstractConsoleAdapter --> pl.cezaryregec.zoo.utils.ReflectionUtils : <<use>>

interface pl.cezaryregec.zoo.console.deserialization.DeserializationLink {
    +deserialize(String input, Class type) : Object
}

class pl.cezaryregec.zoo.console.deserialization.StringDeserializationLink {
    +deserialize(String input, Class type) : Object
}

class pl.cezaryregec.zoo.console.deserialization.IntegerDeserializationLink {
    +deserialize(String input, Class type) : Object
}

class pl.cezaryregec.zoo.console.deserialization.BooleanDeserializationLink {
    +deserialize(String input, Class type) : Object
}

class pl.cezaryregec.zoo.console.deserialization.EnumDeserializationLink {
    +deserialize(String input, Class type) : Object
}

pl.cezaryregec.zoo.console.deserialization.DeserializationLink <|.. pl.cezaryregec.zoo.console.deserialization.StringDeserializationLink
pl.cezaryregec.zoo.console.deserialization.DeserializationLink <|.. pl.cezaryregec.zoo.console.deserialization.IntegerDeserializationLink
pl.cezaryregec.zoo.console.deserialization.DeserializationLink <|.. pl.cezaryregec.zoo.console.deserialization.BooleanDeserializationLink
pl.cezaryregec.zoo.console.deserialization.DeserializationLink <|.. pl.cezaryregec.zoo.console.deserialization.EnumDeserializationLink
pl.cezaryregec.zoo.console.AbstractConsoleAdapter --> pl.cezaryregec.zoo.console.deserialization.DeserializationLink  : <<use>>

interface pl.cezaryregec.zoo.actions.ActionFactory<ActionIndex : Enum> {
    +create(index: ActionIndex) : ActionExecutor
}

class pl.cezaryregec.zoo.actions.ZooActionFactory {
    -{static} EXECUTOR_MAP : Map<ZooActionIndex, ActionExecutor>
    +create(index: ActionIndex) : ActionExecutor
}

pl.cezaryregec.zoo.actions.ZooActionFactory ..|> pl.cezaryregec.zoo.actions.ActionFactory : <<bind>> \n ActionIndex -> ZooActionIndex
pl.cezaryregec.zoo.actions.ZooActionFactory <-- pl.cezaryregec.zoo.console.ZooConsoleAdapter : <<use>>

enum pl.cezaryregec.zoo.actions.ZooActionIndex {
    +GET_MENU
    +ADD_ANIMAL
    +GET_ANIMALS
    +GET_ANIMALS_BY_TYPE
    +REMOVE_ANIMAL
}

pl.cezaryregec.zoo.actions.ZooActionIndex <-- pl.cezaryregec.zoo.actions.ZooActionFactory : <<use>>

class pl.cezaryregec.zoo.dto.result.ResultDto<Result : Serializable> {
    -result : Result
    +toString() : String
    +{static} <Type : Serializable> of(result: Type) : ResultDto<Type>
    +{static} <Type : Serializable> of(result: List<Type>) : ResultDto<Type>
}

class pl.cezaryregec.zoo.dto.result.ListResultDto<Result : Serializable> {
    -result : List<Result>
    +toString() : String
}

pl.cezaryregec.zoo.dto.result.ResultDto ..|> java.io.Serializable
pl.cezaryregec.zoo.dto.result.ResultDto <|-- pl.cezaryregec.zoo.dto.result.ListResultDto

interface pl.cezaryregec.zoo.actions.ActionExecutor<Query : ActionQuery> {
    +execute(query: Query) : ResultDto
}

interface pl.cezaryregec.zoo.actions.ActionQuery

class pl.cezaryregec.zoo.actions.menu.GetMenuQuery

pl.cezaryregec.zoo.actions.menu.GetMenuQuery ..|> pl.cezaryregec.zoo.actions.ActionQuery
pl.cezaryregec.zoo.console.AbstractConsoleAdapter --> pl.cezaryregec.zoo.dto.result.ResultDto : <<use>>

class pl.cezaryregec.zoo.actions.menu.GetMenuActionExecutor {
    +execute(query: GetMenuQuery) : ResultDto
}

class pl.cezaryregec.zoo.actions.menu.MenuDictionary {
    - {static} DICTIONARY : Map<ZooActionIndex, String>

    -<<constructor>> MenuDictionary()
    + {static} get(index : ZooActionIndex) : String
}

class pl.cezaryregec.zoo.actions.menu.MenuItemFormatter {
    -<<constructor>> MenuItemFormatter()
    + {static} map(index : ZooActionIndex)
}

pl.cezaryregec.zoo.actions.menu.GetMenuActionExecutor --> pl.cezaryregec.zoo.actions.menu.MenuItemFormatter : <<use>>
pl.cezaryregec.zoo.actions.menu.MenuItemFormatter --> pl.cezaryregec.zoo.actions.menu.MenuDictionary : <<use>>

pl.cezaryregec.zoo.actions.menu.GetMenuActionExecutor --> pl.cezaryregec.zoo.actions.menu.GetMenuQuery : <<use>>
pl.cezaryregec.zoo.actions.menu.GetMenuActionExecutor ..|> pl.cezaryregec.zoo.actions.ActionExecutor : <<bind>> \n Query -> GetMenuQuery
pl.cezaryregec.zoo.actions.ZooActionFactory --> pl.cezaryregec.zoo.actions.menu.GetMenuActionExecutor : <<create>>

class pl.cezaryregec.zoo.actions.animals.add.AddAnimalQuery {
    -type : AnimalType
    -name : String
    -yearOfBirth : Integer
    -monthOfBirth : Integer
    -dayOfBirth : Integer

    +getType() : AnimalType
    +getName() : String
    +getYearOfBirth() : Integer
    +getMonthOfBirth() : Integer
    +getDayOfBirth() : Integer
}

pl.cezaryregec.zoo.actions.ActionQuery <|.. pl.cezaryregec.zoo.actions.animals.add.AddAnimalQuery

enum pl.cezaryregec.zoo.actions.animals.AnimalType {
    +GIRAFFE
    +ELEPHANT
    +TIGER
}

class .pl.cezaryregec.zoo.actions.animals.AnimalTypeFactory {
    +{static} create(type: AnimalType) : Class
}

pl.cezaryregec.zoo.actions.animals.AnimalType --o pl.cezaryregec.zoo.actions.animals.add.AddAnimalQuery
pl.cezaryregec.zoo.actions.animals.AnimalTypeFactory --> pl.cezaryregec.zoo.actions.animals.AnimalType : <<use>>
pl.cezaryregec.zoo.actions.animals.get.GetAnimalsByTypeActionExecutor --> pl.cezaryregec.zoo.actions.animals.AnimalTypeFactory : <<use>>

class pl.cezaryregec.zoo.actions.animals.add.AddAnimalActionExecutor {
    +execute (query : AddAnimalQuery) : ResultDto
}

pl.cezaryregec.zoo.actions.animals.add.AddAnimalActionExecutor --> pl.cezaryregec.zoo.actions.animals.add.AddAnimalQuery : <<use>>

class pl.cezaryregec.zoo.actions.animals.add.AnimalFactory {
    + {static} create(AddAnimalQuery query) : Animal
}

pl.cezaryregec.zoo.actions.animals.add.AddAnimalActionExecutor --> pl.cezaryregec.zoo.actions.animals.add.AnimalFactory : <<use>>

pl.cezaryregec.zoo.actions.animals.add.AnimalFactory --> pl.cezaryregec.zoo.model.animal.Giraffe : <<create>>
pl.cezaryregec.zoo.actions.animals.add.AnimalFactory --> pl.cezaryregec.zoo.model.animal.Elephant : <<create>>
pl.cezaryregec.zoo.actions.animals.add.AnimalFactory --> pl.cezaryregec.zoo.model.animal.Tiger : <<create>>

pl.cezaryregec.zoo.actions.ZooActionFactory --> pl.cezaryregec.zoo.actions.animals.add.AddAnimalActionExecutor : <<create>>
pl.cezaryregec.zoo.actions.animals.add.AddAnimalActionExecutor ..|> pl.cezaryregec.zoo.actions.ActionExecutor : <<bind>> \n Query -> AddAnimalQuery
pl.cezaryregec.zoo.actions.animals.add.AddAnimalActionExecutor --> pl.cezaryregec.zoo.repository.AnimalRepository : <<use>>

class pl.cezaryregec.zoo.actions.animals.get.GetAnimalsActionExecutor {
    +execute (query : GetAnimalsQuery) : ResultDto
}

pl.cezaryregec.zoo.actions.animals.get.GetAnimalsActionExecutor --> pl.cezaryregec.zoo.actions.animals.get.GetAnimalsQuery : <<use>>

class pl.cezaryregec.zoo.actions.animals.get.GetAnimalsQuery

pl.cezaryregec.zoo.actions.ActionQuery <|.. pl.cezaryregec.zoo.actions.animals.get.GetAnimalsQuery

pl.cezaryregec.zoo.actions.ZooActionFactory --> pl.cezaryregec.zoo.actions.animals.get.GetAnimalsActionExecutor : <<create>>
pl.cezaryregec.zoo.actions.animals.get.GetAnimalsActionExecutor ..|> pl.cezaryregec.zoo.actions.ActionExecutor : <<bind>> \n Query -> GetAnimalsQuery
pl.cezaryregec.zoo.actions.animals.get.GetAnimalsActionExecutor --> pl.cezaryregec.zoo.repository.AnimalRepository : <<use>>

class pl.cezaryregec.zoo.actions.animals.get.GetAnimalsByTypeActionExecutor {
    +execute (query : GetAnimalsByTypeQuery) : ResultDto
}

pl.cezaryregec.zoo.actions.animals.get.GetAnimalsByTypeActionExecutor --> pl.cezaryregec.zoo.actions.animals.get.GetAnimalsByTypeQuery : <<use>>

class pl.cezaryregec.zoo.actions.animals.get.GetAnimalsByTypeQuery {
    -type : AnimalType

    +getType() : AnimalType
}
pl.cezaryregec.zoo.actions.ActionQuery <|.. pl.cezaryregec.zoo.actions.animals.get.GetAnimalsByTypeQuery

pl.cezaryregec.zoo.actions.ZooActionFactory --> pl.cezaryregec.zoo.actions.animals.get.GetAnimalsByTypeActionExecutor : <<create>>
pl.cezaryregec.zoo.actions.animals.get.GetAnimalsByTypeActionExecutor ..|> pl.cezaryregec.zoo.actions.ActionExecutor : <<bind>> \n Query -> GetAnimalsByTypeQuery
pl.cezaryregec.zoo.actions.animals.get.GetAnimalsByTypeActionExecutor --> pl.cezaryregec.zoo.repository.AnimalRepository : <<use>>

class pl.cezaryregec.zoo.actions.animals.remove.RemoveAnimalExecutor {
    +execute (query : RemoveAnimalQuery) : ResultDto
}

pl.cezaryregec.zoo.actions.animals.remove.RemoveAnimalExecutor --> pl.cezaryregec.zoo.actions.animals.remove.RemoveAnimalQuery : <<use>>

class pl.cezaryregec.zoo.actions.animals.remove.RemoveAnimalQuery {
    -name : String

    +getName() : String
}
pl.cezaryregec.zoo.actions.ActionQuery <|.. pl.cezaryregec.zoo.actions.animals.remove.RemoveAnimalQuery

pl.cezaryregec.zoo.actions.ZooActionFactory --> pl.cezaryregec.zoo.actions.animals.remove.RemoveAnimalExecutor : <<create>>
pl.cezaryregec.zoo.actions.animals.remove.RemoveAnimalExecutor ..|> pl.cezaryregec.zoo.actions.ActionExecutor : <<bind>> \n Query -> RemoveAnimalQuery
pl.cezaryregec.zoo.actions.animals.remove.RemoveAnimalExecutor --> pl.cezaryregec.zoo.repository.AnimalRepository : <<use>>

class pl.cezaryregec.zoo.actions.shutdown.ShutdownActionExecutor {
    +execute (query : ExitQuery) : ResultDto
}

pl.cezaryregec.zoo.actions.shutdown.ShutdownActionExecutor --> pl.cezaryregec.zoo.actions.shutdown.ShutdownQuery : <<use>>

class pl.cezaryregec.zoo.actions.shutdown.ShutdownQuery

pl.cezaryregec.zoo.actions.ActionQuery <|.. pl.cezaryregec.zoo.actions.shutdown.ShutdownQuery
pl.cezaryregec.zoo.actions.ZooActionFactory --> pl.cezaryregec.zoo.actions.shutdown.ShutdownActionExecutor : <<create>>


interface pl.cezaryregec.zoo.model.LivingCreature {
    +getBirthday() : Date
    +isAlive() : boolean
}

abstract class pl.cezaryregec.zoo.model.animal.Animal {
    #birthday: Date
    #name: String
    #alive: boolean

    #<<constructor>> Animal(birthday: Date)
    +getName() : String
    +getBirthday() : Date
    +isAlive() : boolean
}

pl.cezaryregec.zoo.model.LivingCreature <|.. pl.cezaryregec.zoo.model.animal.Animal

class pl.cezaryregec.zoo.model.animal.Giraffe {
    +<<constructor>> Giraffe(birthday: Date)
}

class pl.cezaryregec.zoo.model.animal.Elephant {
    +<<constructor>> Elephant(birthday: Date)
}

class pl.cezaryregec.zoo.model.animal.Tiger {
    +<<constructor>> Tiger(birthday: Date)
}

pl.cezaryregec.zoo.model.animal.Animal <|-- pl.cezaryregec.zoo.model.animal.Giraffe
pl.cezaryregec.zoo.model.animal.Animal <|-- pl.cezaryregec.zoo.model.animal.Elephant
pl.cezaryregec.zoo.model.animal.Animal <|-- pl.cezaryregec.zoo.model.animal.Tiger

interface pl.cezaryregec.zoo.repository.Repository<Id : Object, Model : Object> {
    +get(id: Id) : Model
    +get(predicate: Predicate<Model>) : List<Model>
    +getAll() : List<Model>
    +add(model: Model)
    +remove(model: Model)
    +remove(predicate: Predicate<Model>) : boolean
    +removeAll()
}

class pl.cezaryregec.zoo.repository.AnimalRepository {
    -repository : List<Animal>
    +get(id: String) : Animal
    +get(predicate: Predicate<Animal>) : List<Animal>
    +getAll() : List<Animal>
    +add(animal: Animal)
    +remove(animal: Animal)
    +remove(predicate: Predicate<Animal>) : boolean
    +removeAll()
}

pl.cezaryregec.zoo.repository.Repository <|.. pl.cezaryregec.zoo.repository.AnimalRepository : <<bind>> \n Id -> String, \n Model -> Animal
pl.cezaryregec.zoo.repository.AnimalRepository o-- pl.cezaryregec.zoo.model.animal.Animal

left to right direction
hide interface fields
@enduml